### ISSUE TITLE
Looking for a package called 'stackutils'

### ISSUE THREAD

**Issue by edouard-gv** [dgrtwo/tabs-spaces-post#1]
Thank you very much for this project from which I would like to build a small dojo comparing different user friendly tools for data analysis.

While installing a brand new R environment 3.4.3 with RStudio 1.1.383 on windows seven, I had to install packages:
- rmarkdown (seems common sense)
- ggplot2 (why not)

But then when launching knit("README.Rmd") I have the following error:

> Quitting from lines 27-42 (README.Rmd) 
> Error in library(p, character.only = TRUE) : 
>  there is no package called 'stackutils'`

I found no reference to such a package associated with R. Do you have any workaround?

**Comment by hacktuarial** [comment]
You can just remove this line from `cache/__packages`

**Comment by edouard-gv** [comment]
Thank you! Nevertheless, I don't have the environment anymore. I can not test your solution thus. I close it.
